pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home_get_APOD_view, name='home'),
    path('launches-events/', views.launch_event_view, name='launches-events'),
    path('astronauts/', views.astronaut_view, name='astronauts'),
    path('agencies/', views.agency_view, name='agencies'),
    path('iss-location-info/', views.iss_location_info_view, name='iss-location-info'),
]

project_structure/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #URLS for our main app.
    path('', include('pages.urls')),
]

pages/templates/agencies.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load static %}

{% block content %}

<div class="agency-input-form mt-2">
    <form action="{% url 'pages:agencies' %}" method="post" class="form-inline my-2 my-lg-0">
        {% csrf_token %}
        {{ form|crispy }}
        <button name='submit' class='btn btn-dark ml-2 mt-2 mb-2'>Search for Agency</button>
    </form>
</div>

{% if resultCount %}
<h2 class="mb-2" style="text-align: center; color: #DBC8FF;">{{ resultCount }} Results Available</h2>
{% endif %}
{% if featuredCount %}
<h2 class="mb-2" style="text-align: center; color: #DBC8FF;">{{ featuredCount }} Agencies Featured</h2>
{% endif %}

{% if page_obj %}
<div class="container" style="width: auto">
    <div class="row justify-content-center">
        <div class="row">
{% for query in page_obj %}
<div class="col-6">

<div class="card mb-4" style="width: auto; height: auto;">
    <div class="card-header">
        <h4 class="card-title" style="text-align: center; font-style: italic;">{{ query.name }}</h4>
    </div>
    <div class="card-body">
        <div class="img-square-wrapper">
            {% if query.logo %}
            <img class="card-img-top" src="{{ query.logo }}" alt="Rocket Launch">
            {% else %}
            <img class="card-img-top" src="{% static 'img/No_image_available.png' %}" alt="Rocket Launch">
            {% endif %}
        </div>
    </div>
    
    <div class="card-footer">
        
        <p class="card-title" style="text-align: center;">Type: {{ query.type }}</p>
        <h5 class="card-title" style="text-align: center; text-decoration: underline;">{{ query.administrator }}</h5>
        <p class="card-text lead" style="text-align: center;">Founded: {{ query.founding_year }}</p>
        <p class="card-text lead" style="text-align: center;">Abbreviation: {{ query.abbreviation }}</p>
        <hr>
        <p class="card-text lead" style="text-align: center;">Launchers: {{ query.launchers }}</p>
        <p class="card-text lead" style="text-align: center;">SpaceCrafts: {{ query.spacecrafts }}</p>
        <hr>
        <div class="Stats">
            <h5 class="mb-2" id="success">Successful Launches: {{ query.successful_launches }}</h5>
            <h5 class="mb-2" id="failed">Failed Launches: {{ query.failed_launches }}</h5>
            <h5 id="pending">Pending Launches: {{ query.pending_launches }}</h5>
        </div>
        <hr>
        <p class="card-text lead" style="text-align: center;">Home Webpage: <a href="{{query.home_webpage}}">Click Here!</a></p>
        <p class="card-text lead" style="text-align: center;">Wiki Page: <a href="{{query.wiki_page}}">Click Here!</a></p>

    </div>
</div>

</div>
{% empty %}

<h1>No Results Available.</h1>

{% endfor %}  

</div>
</div>
</div>

{% endif %}

<div class="pagination justify-content-center">

    <span class="step-links">
        <ul class="pagination">

        {% if page_obj.has_previous %}
            <a class="page-link" href="?page=1">&laquo; first</a>
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current mx-4" style="align-content: center; color: #DBC8FF;">
            page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}

        </ul>
    </span>

</div>

<style>
    .agency-input-form{
        display: flex;
        justify-content: center;
    }
    .card{
        border-radius: 15px;
        overflow: hidden;
        background-color: #B691FF;
        display: flex;
        flex-direction: column;
    }
    .card-body{
        background-color: #424242;
    }
    .img-square-wrapper{
        display: flex;
        justify-content: center;
    }
    .card-img-top{
        object-fit: contain;
    }
</style>

{% endblock content %}

pages/templates/astronauts.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

<div class="astronaut-input-form mt-2">
  <form action="{% url 'pages:astronauts' %}" method="post" class="form-inline my-2 my-lg-0">
    {% csrf_token %}
    {{ form|crispy }}
    <button name='submit' class='btn btn-dark ml-2 mt-2 mb-2'>Search for Astronaut</button>
  </form>
</div>

{% if resultCount %}
<h2 class="mb-2" style="text-align: center; color: #DBC8FF;">{{ resultCount }} Results Available</h2>
{% endif %}
{% if astronautCount %}
<h2 class="mb-2" style="text-align: center; color: #DBC8FF;">{{ astronautCount }} Astronauts</h2>
{% endif %}

{% if page_obj %}
<div class="container" style="width: 100vw">
    <div class="row justify-content-center">
        
{% for query in page_obj %}

<div class="card mb-4" style="width: 55rem;">
    <div class="card-horizontal">
        <div class="img-square-wrapper">
            {% if query.image %}
            <img class="card-img-top" src="{{ query.image }}" alt="Astronaut">
            {% endif %}
        </div>
        <div class="card-body">
            <h4 class="card-title" style="text-align: center;">{{ query.name }}</h4>
            <p class="card-text lead mb-4" style="text-align: center; font-style: italic;">{{ query.status }}</p>
            <h5 class="card-title" style="text-align: center; text-decoration: underline;">{{ query.nationality }}</h5>
            <hr>
            <p class="card-title" style="text-align: center; text-decoration: underline;">{{ query.agency }}</p>
            <p class="card-text lead mb-4" style="text-align: center;">Age: {{ query.age }}</p>
            <p class="card-text lead mb-4" style="text-align: center;">DOB: {{ query.date_of_birth }}</p>
            {% if query.date_of_death %}
            <p class="card-text lead mb-4" style="text-align: center;">DOD: {{ query.date_of_death }}</p>
            {% endif %}
        </div>
    </div>
    <div class="card-footer">
        <p class="card-text-bio lead mb-4" style="text-align: center;">{{ query.bio }}</p>
    </div>
</div>

{% empty %}

<h1>No Results Available.</h1>

{% endfor %}  

</div>
</div>

{% endif %}

{% if page_obj %}

<div class="pagination justify-content-center">

    <span class="step-links">
        <ul class="pagination">

        {% if page_obj.has_previous %}
            <a class="page-link" href="?page=1">&laquo; first</a>
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current mx-4" style="align-content: center; color: #DBC8FF;">
            page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}

        </ul>
    </span>

</div>

{% endif %}

<style>
    .card {
        border-radius: 15px 75px;
        overflow: hidden;
    }
    .astronaut-input-form {
        display: flex;
        justify-content: center;
    }
    .card-body {
        background-color: #B691FF;
    }
    .card-footer {
        background-color: #4E0076;
    }
    .card-text-bio {
        color: #F0EDE5;
    }
</style>

{% endblock content %}

pages/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" type="text/css" href="../static/css/jquery.countdown.css">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script type="text/javascript" src="../static/js/jquery.plugin.js"></script>
    <script type="text/javascript" src="../static/js/jquery.countdown.js"></script>

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
     integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI="
     crossorigin=""/>
     <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"
     integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM="
     crossorigin=""></script>

    <title>Cosmos</title>

  </head>
  <body>
    
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'pages:home' %}">Cosmos-Launchpad</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'pages:home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'pages:launches-events' %}">Launches/Events</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'pages:astronauts' %}">Astronauts</a>
              </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:agencies' %}">Space Agencies</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:iss-location-info' %}">ISS location/Astronauts</a>
                </li>
              </ul>
            </div>
          </nav>
    </header>

    <div>
        {% block content %}
        {% endblock content %}
    </div>
   
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

  </body>
</html>

pages/templates/home.html
{% extends "base.html" %}

{% block content %}

<div class="container">
<div class="row">

<div class="col-md-6">
<div class="jumbotron mx-auto mt-5" style="max-height: fit-content; min-width: 300px; max-width: 500px">
    <h1 class="display-4 mb-3" style="text-align: center; color: #DBC8FF;">Welcome to Cosmos-LaunchPad!</h1>
    <hr class="my-4">
    <h2 class="lead" style="text-align: center; color: #DBC8FF;">Cosmos is a web-application that will provide users with data on previous and upcoming launches along with a database of information on astronauts and space agencies that have been active at some point or another.</h2>
    <p class="lead mt-2" style="text-align: center; color: #DBC8FF;">The application will also provide the real-time location of the ISS around the earth along with NASA's astronomy picture of the day and the current population of people in space.</p>
    <hr>
</div>
</div>

<div class="col-md-6">

<div class="card mt-2" style="min-width: 300px; color: #DBC8FF; background-color: #433445;">
    <div class="card-header">
        <h1 class="lead mb-2" style="text-align: center; font-weight: bold; color: #DBC8FF;">NASA's "Astronomy Picture of the Day"</h1>
    </div>
        <img src="{{ jsonResponse.url }}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title" style="text-align: center; font-weight: bold;">{{ jsonResponse.title }}</h5>
            <hr>

        {% if jsonResponse.copyright %}
            <h5 class="card-title" style="text-align: center; font-weight: bold;">By: {{ jsonResponse.copyright }}</h5>
        {% endif %}

        <p class="card-text" style="text-align: center;">{{ jsonResponse.explanation }}</p>
        <hr>
        <p class="card-text" style="text-align: center;">Today's Date: {{ jsonResponse.date }}</p>
        </div>
    </div>
</div>

</div>
</div>

<style>
    .jumbotron {
        background-color: #4E0076;
    }
</style>

{% endblock content %}

pages/templates/iss-location-astronauts.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<h1 class="mt-2" style="text-align: center; color: #DBC8FF;">ISS Location and current in space Astronauts</h1>

<h2 class="mb-2" style="text-align: center; color: #DBC8FF;">There are {{ jsonResponse.number }} people in space right now!</h2>

<table class="table table-hover table-sm" style="background-color: #4E0076;">
    <thead class="thead-dark">
      <tr>
        <th scope="col" style="text-align: center;">Full-Name</th>
        <th scope="col">Space-Craft</th>
      </tr>
    </thead>
    <tbody>
      {% for person in jsonResponse.people %}
        <tr>
            <td style="text-align: center; color: #DBC8FF;">{{ person.name }}</td>
            <td style="color: #DBC8FF;">{{ person.craft }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <div id="map"></div>
  
  <style>

    #map {
      height: 500px;
    }

  </style>
  <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
  <script>

    var world_street_map = L.tileLayer('Http://services.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}', {
      attribution: "Tiles &copy; Esri &mdash; Source: Esri, Delorme, NAVTEQ, USGS, Intermap, iPC, NRCAN, Esri Japan, METI, Esri China (Hong Kong), Esri (Thailand), TomTom, 2012"
    });

    var map = L.map('map', {
      layers: [world_street_map]
    }).setView([0, 0], 2)

    var issIcon = L.icon({iconUrl: "{% static 'img/ISS.jpeg' %}", iconSize:[40, 40]});
    var issMark = L.marker([0, 0], {icon: issIcon}).addTo(map);
    
    var issCircle = L.circleMarker([0,0], {
      color: 'blue',
      fillColor: '#A020F0',
      fillOpacity: 0.5,
      radius: 50
    }).addTo(map);

    function trackISS () {
      $.getJSON('http://api.open-notify.org/iss-now.json?callback=?', function(data) {

        var longitude = data['iss_position']['longitude'];
        var latitude = data['iss_position']['latitude'];

        issMark.setLatLng([latitude, longitude]);
        issCircle.setLatLng([latitude, longitude]);

        map.panTo([latitude, longitude], animate=true);
        
      });
     
    }
    trackISS();
    setInterval(trackISS, 5000);
  </script>

{% endblock content %}

pages/templates/launches-events.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

<div class="launch-input-form mt-2">
    <form action="{% url 'pages:launches-events' %}" method="post" class="form-inline my-2 my-lg-0">
        {% csrf_token %}
        {{ form|crispy }}
        <button name='submit' class='btn btn-dark ml-2 mt-2 mb-2'>Search for Launch</button>
    </form>
</div>

{% if resultCount %}
<h2 class="mt-2 mb-2" style="text-align: center; color: #DBC8FF;">{{ resultCount }} Results Available</h2>
{% endif %}
{% if upcomingCount %}
<h2 class="mt-2 mb-2" style="text-align: center; color: #DBC8FF;">{{ upcomingCount }} Upcoming Launches</h2>
{% endif %}

{% if page_obj %}
<div class="container" style="width: 100vw">
    <div class="row justify-content-center">
        
{% for query in page_obj %}

<div class="card mb-4" style="width: 55rem;">
    <div class="card-horizontal">
        <div class="img-square-wrapper">
            {% if query.image %}
            <img class="card-img-top" src="{{ query.image }}" alt="Rocket Launch">
            {% endif %}
        </div>
        <div class="card-body">
            <h4 class="card-title" style="text-align: center; color: #DBC8FF;">{{ query.name }}</h4>
            <h5 class="card-title" style="text-align: center; text-decoration: underline; color: #DBC8FF;">{{ query.launch_provider }}</h5>
            <hr>
            <p class="card-title" style="text-align: center; color: #DBC8FF;">{{ query.launch_location }}</p>
            <p class="card-text lead mb-4" style="text-align: center; color: #DBC8FF;">Scheduled Date: {{ query.launch_date_time }}</p>

            <div class="mb-4">
                <td><div class="launchCountdown" start="{{ query.launch_date_time }}"></div></td>
            </div>

            <p class="card-text lead" style="text-align: center; color: #DBC8FF;">Launch Status: {{ query.launch_status }}</p>
        </div>
    </div>
    <div class="card-footer">
        {% if query.stream_url %}
            <div style="text-align: center;">
                <a href="{{ query.stream_url }}"><button class="btn btn-success">View Stream</button></a>
            </div>
        {% else %}
            <p style="text-align: center; padding-top: 10px; padding-bottom: 10px;">
                <small class="text-muted">No Stream available for this launch!</small>
            </p>    
        {% endif %}
    </div>
</div>



{% empty %}

<h1>No Results Available.</h1>

{% endfor %}
        
</div>
</div>  
  
{% endif %}

{% if page_obj %}

<div class="pagination justify-content-center">

    <span class="step-links">
        <ul class="pagination">

        {% if page_obj.has_previous %}
            <a class="page-link" href="?page=1">&laquo; first</a>
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current mx-4" style="align-content: center; color: #DBC8FF;">
            page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}

        </ul>
    </span>

</div>

{% endif %}

<script>
    $('.launchCountdown').each(function() {
    this == $(this);
    var launch_date = $(this).attr('start');
    var matchDate = new Date(launch_date);
    $(this).countdown({
        until: matchDate,
        description: 'Until Liftoff!'
    });
});
</script>

<style>
    .launch-input-form{
        display: flex;
        justify-content: center;
    }
    .card{
        border-radius: 15px 75px;
        overflow: hidden;
    }
    .card-horizontal{
        background-color: #4E0076;
    }
    .card-footer{
        background-color: #433445;
    }
    body{
        text-align: center;
        font-family: sans-serif;
        font-weight: 100;
    }
    h1{
        color: #396;
        font-weight: 100;
        font-size: 40px;
        margin: 40px 0px 20px;
    }
     #clockdiv{
        font-family: sans-serif;
        color: #fff;
        display: inline-block;
        font-weight: 100;
        text-align: center;
        font-size: 30px;
    }
    #clockdiv > div{
        padding: 10px;
        border-radius: 3px;
        background: #00BF96;
        display: inline-block;
    }
    #clockdiv div > span{
        padding: 15px;
        border-radius: 3px;
        background: #00816A;
        display: inline-block;
    }
    smalltext{
        padding-top: 5px;
        font-size: 16px;
    }
    </style>

{% endblock content %}